var Path={}
const path=require("path");
Path.rootSpace=path.dirname(__dirname)+"/";
Path.jsFolder=`${Path.rootSpace}js/`;
Path.functionsFolder=`${Path.rootSpace}functions/`;
Path.dataFolder=`${Path.rootSpace}data/`
Path.settings=`${Path.dataFolder}settings.json`;
Path.dictFolder=`${Path.rootSpace}dict/`;
Path.pythonScriptsFolder=`${Path.rootSpace}NLP/`
module.exports=Path;
